# iso_country_list.sql
#
# This will create and then populate a MySQL table with a list of the names and
# ISO 3166 codes for countries in existence as of the date below.
#
# Usage:
#    mysql -u username -ppassword database_name < ./iso_country_list.sql
#
# For updates to this file, see http://27.org/isocountrylist/
# For more about ISO 3166, see http://www.iso.ch/iso/en/prods-services/iso3166ma/02iso-3166-code-lists/list-en1.html
#
# Created by getisocountrylist.pl on Sun Nov  2 14:59:20 2003.
# Wm. Rhodes <iso_country_list@27.org>
#

CREATE TABLE IF NOT EXISTS countries (
  iso CHAR(2) NOT NULL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  printable_name VARCHAR(80) NOT NULL,
  iso3 CHAR(3),
  numcode SMALLINT
);

INSERT INTO countries VALUES (0,'AF','AFGHANISTAN','Afghanistan','AFG','004');
INSERT INTO countries VALUES (0,'AL','ALBANIA','Albania','ALB','008');
INSERT INTO countries VALUES (0,'DZ','ALGERIA','Algeria','DZA','012');
INSERT INTO countries VALUES (0,'AS','AMERICAN SAMOA','American Samoa','ASM','016');
INSERT INTO countries VALUES (0,'AD','ANDORRA','Andorra','AND','020');
INSERT INTO countries VALUES (0,'AO','ANGOLA','Angola','AGO','024');
INSERT INTO countries VALUES (0,'AI','ANGUILLA','Anguilla','AIA','660');
INSERT INTO countries VALUES (0,'AQ','ANTARCTICA','Antarctica',NULL,NULL);
INSERT INTO countries VALUES (0,'AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','028');
INSERT INTO countries VALUES (0,'AR','ARGENTINA','Argentina','ARG','032');
INSERT INTO countries VALUES (0,'AM','ARMENIA','Armenia','ARM','051');
INSERT INTO countries VALUES (0,'AW','ARUBA','Aruba','ABW','533');
INSERT INTO countries VALUES (0,'AU','AUSTRALIA','Australia','AUS','036');
INSERT INTO countries VALUES (0,'AT','AUSTRIA','Austria','AUT','040');
INSERT INTO countries VALUES (0,'AZ','AZERBAIJAN','Azerbaijan','AZE','031');
INSERT INTO countries VALUES (0,'BS','BAHAMAS','Bahamas','BHS','044');
INSERT INTO countries VALUES (0,'BH','BAHRAIN','Bahrain','BHR','048');
INSERT INTO countries VALUES (0,'BD','BANGLADESH','Bangladesh','BGD','050');
INSERT INTO countries VALUES (0,'BB','BARBADOS','Barbados','BRB','052');
INSERT INTO countries VALUES (0,'BY','BELARUS','Belarus','BLR','112');
INSERT INTO countries VALUES (0,'BE','BELGIUM','Belgium','BEL','056');
INSERT INTO countries VALUES (0,'BZ','BELIZE','Belize','BLZ','084');
INSERT INTO countries VALUES (0,'BJ','BENIN','Benin','BEN','204');
INSERT INTO countries VALUES (0,'BM','BERMUDA','Bermuda','BMU','060');
INSERT INTO countries VALUES (0,'BT','BHUTAN','Bhutan','BTN','064');
INSERT INTO countries VALUES (0,'BO','BOLIVIA','Bolivia','BOL','068');
INSERT INTO countries VALUES (0,'BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','070');
INSERT INTO countries VALUES (0,'BW','BOTSWANA','Botswana','BWA','072');
INSERT INTO countries VALUES (0,'BV','BOUVET ISLAND','Bouvet Island',NULL,NULL);
INSERT INTO countries VALUES (0,'BR','BRAZIL','Brazil','BRA','076');
INSERT INTO countries VALUES (0,'IO','BRITISH INDIAN OCEAN TERRITORY','British Indian Ocean Territory',NULL,NULL);
INSERT INTO countries VALUES (0,'BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','096');
INSERT INTO countries VALUES (0,'BG','BULGARIA','Bulgaria','BGR','100');
INSERT INTO countries VALUES (0,'BF','BURKINA FASO','Burkina Faso','BFA','854');
INSERT INTO countries VALUES (0,'BI','BURUNDI','Burundi','BDI','108');
INSERT INTO countries VALUES (0,'KH','CAMBODIA','Cambodia','KHM','116');
INSERT INTO countries VALUES (0,'CM','CAMEROON','Cameroon','CMR','120');
INSERT INTO countries VALUES (0,'CA','CANADA','Canada','CAN','124');
INSERT INTO countries VALUES (0,'CV','CAPE VERDE','Cape Verde','CPV','132');
INSERT INTO countries VALUES (0,'KY','CAYMAN ISLANDS','Cayman Islands','CYM','136');
INSERT INTO countries VALUES (0,'CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140');
INSERT INTO countries VALUES (0,'TD','CHAD','Chad','TCD','148');
INSERT INTO countries VALUES (0,'CL','CHILE','Chile','CHL','152');
INSERT INTO countries VALUES (0,'CN','CHINA','China','CHN','156');
INSERT INTO countries VALUES (0,'CX','CHRISTMAS ISLAND','Christmas Island',NULL,NULL);
INSERT INTO countries VALUES (0,'CC','COCOS (KEELING) ISLANDS','Cocos (Keeling) Islands',NULL,NULL);
INSERT INTO countries VALUES (0,'CO','COLOMBIA','Colombia','COL','170');
INSERT INTO countries VALUES (0,'KM','COMOROS','Comoros','COM','174');
INSERT INTO countries VALUES (0,'CG','CONGO','Congo','COG','178');
INSERT INTO countries VALUES (0,'CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180');
INSERT INTO countries VALUES (0,'CK','COOK ISLANDS','Cook Islands','COK','184');
INSERT INTO countries VALUES (0,'CR','COSTA RICA','Costa Rica','CRI','188');
INSERT INTO countries VALUES (0,'CI','COTE D\'IVOIRE','Cote D\'Ivoire','CIV','384');
INSERT INTO countries VALUES (0,'HR','CROATIA','Croatia','HRV','191');
INSERT INTO countries VALUES (0,'CU','CUBA','Cuba','CUB','192');
INSERT INTO countries VALUES (0,'CY','CYPRUS','Cyprus','CYP','196');
INSERT INTO countries VALUES (0,'CZ','CZECH REPUBLIC','Czech Republic','CZE','203');
INSERT INTO countries VALUES (0,'DK','DENMARK','Denmark','DNK','208');
INSERT INTO countries VALUES (0,'DJ','DJIBOUTI','Djibouti','DJI','262');
INSERT INTO countries VALUES (0,'DM','DOMINICA','Dominica','DMA','212');
INSERT INTO countries VALUES (0,'DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214');
INSERT INTO countries VALUES (0,'EC','ECUADOR','Ecuador','ECU','218');
INSERT INTO countries VALUES (0,'EG','EGYPT','Egypt','EGY','818');
INSERT INTO countries VALUES (0,'SV','EL SALVADOR','El Salvador','SLV','222');
INSERT INTO countries VALUES (0,'GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226');
INSERT INTO countries VALUES (0,'ER','ERITREA','Eritrea','ERI','232');
INSERT INTO countries VALUES (0,'EE','ESTONIA','Estonia','EST','233');
INSERT INTO countries VALUES (0,'ET','ETHIOPIA','Ethiopia','ETH','231');
INSERT INTO countries VALUES (0,'FK','FALKLAND ISLANDS (MALVINAS)','Falkland Islands (Malvinas)','FLK','238');
INSERT INTO countries VALUES (0,'FO','FAROE ISLANDS','Faroe Islands','FRO','234');
INSERT INTO countries VALUES (0,'FJ','FIJI','Fiji','FJI','242');
INSERT INTO countries VALUES (0,'FI','FINLAND','Finland','FIN','246');
INSERT INTO countries VALUES (0,'FR','FRANCE','France','FRA','250');
INSERT INTO countries VALUES (0,'GF','FRENCH GUIANA','French Guiana','GUF','254');
INSERT INTO countries VALUES (0,'PF','FRENCH POLYNESIA','French Polynesia','PYF','258');
INSERT INTO countries VALUES (0,'TF','FRENCH SOUTHERN TERRITORIES','French Southern Territories',NULL,NULL);
INSERT INTO countries VALUES (0,'GA','GABON','Gabon','GAB','266');
INSERT INTO countries VALUES (0,'GM','GAMBIA','Gambia','GMB','270');
INSERT INTO countries VALUES (0,'GE','GEORGIA','Georgia','GEO','268');
INSERT INTO countries VALUES (0,'DE','GERMANY','Germany','DEU','276');
INSERT INTO countries VALUES (0,'GH','GHANA','Ghana','GHA','288');
INSERT INTO countries VALUES (0,'GI','GIBRALTAR','Gibraltar','GIB','292');
INSERT INTO countries VALUES (0,'GR','GREECE','Greece','GRC','300');
INSERT INTO countries VALUES (0,'GL','GREENLAND','Greenland','GRL','304');
INSERT INTO countries VALUES (0,'GD','GRENADA','Grenada','GRD','308');
INSERT INTO countries VALUES (0,'GP','GUADELOUPE','Guadeloupe','GLP','312');
INSERT INTO countries VALUES (0,'GU','GUAM','Guam','GUM','316');
INSERT INTO countries VALUES (0,'GT','GUATEMALA','Guatemala','GTM','320');
INSERT INTO countries VALUES (0,'GN','GUINEA','Guinea','GIN','324');
INSERT INTO countries VALUES (0,'GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624');
INSERT INTO countries VALUES (0,'GY','GUYANA','Guyana','GUY','328');
INSERT INTO countries VALUES (0,'HT','HAITI','Haiti','HTI','332');
INSERT INTO countries VALUES (0,'HM','HEARD ISLAND AND MCDONALD ISLANDS','Heard Island and Mcdonald Islands',NULL,NULL);
INSERT INTO countries VALUES (0,'VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT','336');
INSERT INTO countries VALUES (0,'HN','HONDURAS','Honduras','HND','340');
INSERT INTO countries VALUES (0,'HK','HONG KONG','Hong Kong','HKG','344');
INSERT INTO countries VALUES (0,'HU','HUNGARY','Hungary','HUN','348');
INSERT INTO countries VALUES (0,'IS','ICELAND','Iceland','ISL','352');
INSERT INTO countries VALUES (0,'IN','INDIA','India','IND','356');
INSERT INTO countries VALUES (0,'ID','INDONESIA','Indonesia','IDN','360');
INSERT INTO countries VALUES (0,'IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364');
INSERT INTO countries VALUES (0,'IQ','IRAQ','Iraq','IRQ','368');
INSERT INTO countries VALUES (0,'IE','IRELAND','Ireland','IRL','372');
INSERT INTO countries VALUES (0,'IL','ISRAEL','Israel','ISR','376');
INSERT INTO countries VALUES (0,'IT','ITALY','Italy','ITA','380');
INSERT INTO countries VALUES (0,'JM','JAMAICA','Jamaica','JAM','388');
INSERT INTO countries VALUES (0,'JP','JAPAN','Japan','JPN','392');
INSERT INTO countries VALUES (0,'JO','JORDAN','Jordan','JOR','400');
INSERT INTO countries VALUES (0,'KZ','KAZAKHSTAN','Kazakhstan','KAZ','398');
INSERT INTO countries VALUES (0,'KE','KENYA','Kenya','KEN','404');
INSERT INTO countries VALUES (0,'KI','KIRIBATI','Kiribati','KIR','296');
INSERT INTO countries VALUES (0,'KP','KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','Korea, Democratic People\'s Republic of','PRK','408');
INSERT INTO countries VALUES (0,'KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410');
INSERT INTO countries VALUES (0,'KW','KUWAIT','Kuwait','KWT','414');
INSERT INTO countries VALUES (0,'KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417');
INSERT INTO countries VALUES (0,'LA','LAO PEOPLE\'S DEMOCRATIC REPUBLIC','Lao People\'s Democratic Republic','LAO','418');
INSERT INTO countries VALUES (0,'LV','LATVIA','Latvia','LVA','428');
INSERT INTO countries VALUES (0,'LB','LEBANON','Lebanon','LBN','422');
INSERT INTO countries VALUES (0,'LS','LESOTHO','Lesotho','LSO','426');
INSERT INTO countries VALUES (0,'LR','LIBERIA','Liberia','LBR','430');
INSERT INTO countries VALUES (0,'LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434');
INSERT INTO countries VALUES (0,'LI','LIECHTENSTEIN','Liechtenstein','LIE','438');
INSERT INTO countries VALUES (0,'LT','LITHUANIA','Lithuania','LTU','440');
INSERT INTO countries VALUES (0,'LU','LUXEMBOURG','Luxembourg','LUX','442');
INSERT INTO countries VALUES (0,'MO','MACAO','Macao','MAC','446');
INSERT INTO countries VALUES (0,'MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807');
INSERT INTO countries VALUES (0,'MG','MADAGASCAR','Madagascar','MDG','450');
INSERT INTO countries VALUES (0,'MW','MALAWI','Malawi','MWI','454');
INSERT INTO countries VALUES (0,'MY','MALAYSIA','Malaysia','MYS','458');
INSERT INTO countries VALUES (0,'MV','MALDIVES','Maldives','MDV','462');
INSERT INTO countries VALUES (0,'ML','MALI','Mali','MLI','466');
INSERT INTO countries VALUES (0,'MT','MALTA','Malta','MLT','470');
INSERT INTO countries VALUES (0,'MH','MARSHALL ISLANDS','Marshall Islands','MHL','584');
INSERT INTO countries VALUES (0,'MQ','MARTINIQUE','Martinique','MTQ','474');
INSERT INTO countries VALUES (0,'MR','MAURITANIA','Mauritania','MRT','478');
INSERT INTO countries VALUES (0,'MU','MAURITIUS','Mauritius','MUS','480');
INSERT INTO countries VALUES (0,'YT','MAYOTTE','Mayotte',NULL,NULL);
INSERT INTO countries VALUES (0,'MX','MEXICO','Mexico','MEX','484');
INSERT INTO countries VALUES (0,'FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583');
INSERT INTO countries VALUES (0,'MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498');
INSERT INTO countries VALUES (0,'MC','MONACO','Monaco','MCO','492');
INSERT INTO countries VALUES (0,'MN','MONGOLIA','Mongolia','MNG','496');
INSERT INTO countries VALUES (0,'MS','MONTSERRAT','Montserrat','MSR','500');
INSERT INTO countries VALUES (0,'MA','MOROCCO','Morocco','MAR','504');
INSERT INTO countries VALUES (0,'MZ','MOZAMBIQUE','Mozambique','MOZ','508');
INSERT INTO countries VALUES (0,'MM','MYANMAR','Myanmar','MMR','104');
INSERT INTO countries VALUES (0,'NA','NAMIBIA','Namibia','NAM','516');
INSERT INTO countries VALUES (0,'NR','NAURU','Nauru','NRU','520');
INSERT INTO countries VALUES (0,'NP','NEPAL','Nepal','NPL','524');
INSERT INTO countries VALUES (0,'NL','NETHERLANDS','Netherlands','NLD','528');
INSERT INTO countries VALUES (0,'AN','NETHERLANDS ANTILLES','Netherlands Antilles','ANT','530');
INSERT INTO countries VALUES (0,'NC','NEW CALEDONIA','New Caledonia','NCL','540');
INSERT INTO countries VALUES (0,'NZ','NEW ZEALAND','New Zealand','NZL','554');
INSERT INTO countries VALUES (0,'NI','NICARAGUA','Nicaragua','NIC','558');
INSERT INTO countries VALUES (0,'NE','NIGER','Niger','NER','562');
INSERT INTO countries VALUES (0,'NG','NIGERIA','Nigeria','NGA','566');
INSERT INTO countries VALUES (0,'NU','NIUE','Niue','NIU','570');
INSERT INTO countries VALUES (0,'NF','NORFOLK ISLAND','Norfolk Island','NFK','574');
INSERT INTO countries VALUES (0,'MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580');
INSERT INTO countries VALUES (0,'NO','NORWAY','Norway','NOR','578');
INSERT INTO countries VALUES (0,'OM','OMAN','Oman','OMN','512');
INSERT INTO countries VALUES (0,'PK','PAKISTAN','Pakistan','PAK','586');
INSERT INTO countries VALUES (0,'PW','PALAU','Palau','PLW','585');
INSERT INTO countries VALUES (0,'PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied',NULL,NULL);
INSERT INTO countries VALUES (0,'PA','PANAMA','Panama','PAN','591');
INSERT INTO countries VALUES (0,'PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598');
INSERT INTO countries VALUES (0,'PY','PARAGUAY','Paraguay','PRY','600');
INSERT INTO countries VALUES (0,'PE','PERU','Peru','PER','604');
INSERT INTO countries VALUES (0,'PH','PHILIPPINES','Philippines','PHL','608');
INSERT INTO countries VALUES (0,'PN','PITCAIRN','Pitcairn','PCN','612');
INSERT INTO countries VALUES (0,'PL','POLAND','Poland','POL','616');
INSERT INTO countries VALUES (0,'PT','PORTUGAL','Portugal','PRT','620');
INSERT INTO countries VALUES (0,'PR','PUERTO RICO','Puerto Rico','PRI','630');
INSERT INTO countries VALUES (0,'QA','QATAR','Qatar','QAT','634');
INSERT INTO countries VALUES (0,'RE','REUNION','Reunion','REU','638');
INSERT INTO countries VALUES (0,'RO','ROMANIA','Romania','ROM','642');
INSERT INTO countries VALUES (0,'RU','RUSSIAN FEDERATION','Russian Federation','RUS','643');
INSERT INTO countries VALUES (0,'RW','RWANDA','Rwanda','RWA','646');
INSERT INTO countries VALUES (0,'SH','SAINT HELENA','Saint Helena','SHN','654');
INSERT INTO countries VALUES (0,'KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659');
INSERT INTO countries VALUES (0,'LC','SAINT LUCIA','Saint Lucia','LCA','662');
INSERT INTO countries VALUES (0,'PM','SAINT PIERRE AND MIQUELON','Saint Pierre and Miquelon','SPM','666');
INSERT INTO countries VALUES (0,'VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670');
INSERT INTO countries VALUES (0,'WS','SAMOA','Samoa','WSM','882');
INSERT INTO countries VALUES (0,'SM','SAN MARINO','San Marino','SMR','674');
INSERT INTO countries VALUES (0,'ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678');
INSERT INTO countries VALUES (0,'SA','SAUDI ARABIA','Saudi Arabia','SAU','682');
INSERT INTO countries VALUES (0,'SN','SENEGAL','Senegal','SEN','686');
INSERT INTO countries VALUES (0,'CS','SERBIA AND MONTENEGRO','Serbia and Montenegro',NULL,NULL);
INSERT INTO countries VALUES (0,'SC','SEYCHELLES','Seychelles','SYC','690');
INSERT INTO countries VALUES (0,'SL','SIERRA LEONE','Sierra Leone','SLE','694');
INSERT INTO countries VALUES (0,'SG','SINGAPORE','Singapore','SGP','702');
INSERT INTO countries VALUES (0,'SK','SLOVAKIA','Slovakia','SVK','703');
INSERT INTO countries VALUES (0,'SI','SLOVENIA','Slovenia','SVN','705');
INSERT INTO countries VALUES (0,'SB','SOLOMON ISLANDS','Solomon Islands','SLB','090');
INSERT INTO countries VALUES (0,'SO','SOMALIA','Somalia','SOM','706');
INSERT INTO countries VALUES (0,'ZA','SOUTH AFRICA','South Africa','ZAF','710');
INSERT INTO countries VALUES (0,'GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','South Georgia and the South Sandwich Islands',NULL,NULL);
INSERT INTO countries VALUES (0,'ES','SPAIN','Spain','ESP','724');
INSERT INTO countries VALUES (0,'LK','SRI LANKA','Sri Lanka','LKA','144');
INSERT INTO countries VALUES (0,'SD','SUDAN','Sudan','SDN','736');
INSERT INTO countries VALUES (0,'SR','SURINAME','Suriname','SUR','740');
INSERT INTO countries VALUES (0,'SJ','SVALBARD AND JAN MAYEN','Svalbard and Jan Mayen','SJM','744');
INSERT INTO countries VALUES (0,'SZ','SWAZILAND','Swaziland','SWZ','748');
INSERT INTO countries VALUES (0,'SE','SWEDEN','Sweden','SWE','752');
INSERT INTO countries VALUES (0,'CH','SWITZERLAND','Switzerland','CHE','756');
INSERT INTO countries VALUES (0,'SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760');
INSERT INTO countries VALUES (0,'TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN','158');
INSERT INTO countries VALUES (0,'TJ','TAJIKISTAN','Tajikistan','TJK','762');
INSERT INTO countries VALUES (0,'TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834');
INSERT INTO countries VALUES (0,'TH','THAILAND','Thailand','THA','764');
INSERT INTO countries VALUES (0,'TL','TIMOR-LESTE','Timor-Leste',NULL,NULL);
INSERT INTO countries VALUES (0,'TG','TOGO','Togo','TGO','768');
INSERT INTO countries VALUES (0,'TK','TOKELAU','Tokelau','TKL','772');
INSERT INTO countries VALUES (0,'TO','TONGA','Tonga','TON','776');
INSERT INTO countries VALUES (0,'TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780');
INSERT INTO countries VALUES (0,'TN','TUNISIA','Tunisia','TUN','788');
INSERT INTO countries VALUES (0,'TR','TURKEY','Turkey','TUR','792');
INSERT INTO countries VALUES (0,'TM','TURKMENISTAN','Turkmenistan','TKM','795');
INSERT INTO countries VALUES (0,'TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796');
INSERT INTO countries VALUES (0,'TV','TUVALU','Tuvalu','TUV','798');
INSERT INTO countries VALUES (0,'UG','UGANDA','Uganda','UGA','800');
INSERT INTO countries VALUES (0,'UA','UKRAINE','Ukraine','UKR','804');
INSERT INTO countries VALUES (0,'AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784');
INSERT INTO countries VALUES (0,'GB','UNITED KINGDOM','United Kingdom','GBR','826');
INSERT INTO countries VALUES (0,'US','UNITED STATES','United States','USA','840');
INSERT INTO countries VALUES (0,'UM','UNITED STATES MINOR OUTLYING ISLANDS','United States Minor Outlying Islands',NULL,NULL);
INSERT INTO countries VALUES (0,'UY','URUGUAY','Uruguay','URY','858');
INSERT INTO countries VALUES (0,'UZ','UZBEKISTAN','Uzbekistan','UZB','860');
INSERT INTO countries VALUES (0,'VU','VANUATU','Vanuatu','VUT','548');
INSERT INTO countries VALUES (0,'VE','VENEZUELA','Venezuela','VEN','862');
INSERT INTO countries VALUES (0,'VN','VIET NAM','Viet Nam','VNM','704');
INSERT INTO countries VALUES (0,'VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','092');
INSERT INTO countries VALUES (0,'VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850');
INSERT INTO countries VALUES (0,'WF','WALLIS AND FUTUNA','Wallis and Futuna','WLF','876');
INSERT INTO countries VALUES (0,'EH','WESTERN SAHARA','Western Sahara','ESH','732');
INSERT INTO countries VALUES (0,'YE','YEMEN','Yemen','YEM','887');
INSERT INTO countries VALUES (0,'ZM','ZAMBIA','Zambia','ZMB','894');
INSERT INTO countries VALUES (0,'ZW','ZIMBABWE','Zimbabwe','ZWE','716');
